### ISSUE TITLE
Connecting to multiple channels?

### ISSUE THREAD

**Issue by haydencarlson** [ndhays/redux-cablecar#3]
HI i'm using cable car for my app.

I see it's not possible to connect cable car to multiple channels now, or am I wrong about that.

I have two .connects() to different channels.
When I dispatch an action in redux the prefix never matches because only the last `car` gets saved in the `let car;`

Example:
```
reduxCableCar.connect(store, 'Channel1', options)

reduxCableCar.connect(store, 'Channel2', options)
```

In this case I can only dispatch actions through channel2.

I'm going to work on a solution. Just thought I would put that out there incase anyone else was having the same trouble.

**Comment by ndhays** [comment]
Hi @haydencarlson -- woah - did not see this, sorry for such a late response! Absolutely great point. Did you create a solution for it?

I am thinking the middleware should keep track of all connected cars, and then each car must match a `channel` parameter in the action should (in addition to the prefix), and maybe have it be optional with the default broadcast to all channels..

Let me know your status on this, otherwise I will work on the fix. Thanks!

**Comment by haydencarlson** [comment]
Hey @ndhays . Thanks for getting back. I've been really busy and haven't had time to look at it. I haven't had to deal with both of my channels yet through cable car so Its not top priority. I like the solution you proposed though. You should implement it, i'd like to test it out.

**Comment by ndhays** [comment]
Hey @haydencarlson, not sure if you're still interested, but I made some changes w/ a new version that adds a Dispatcher object so you can have multiple connections.

Still a wip, but take a look
